services:
  automation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uber-tech-automation
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: ["bun", "start"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"